version: "3.2"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
  app:
    build: .
    image: app
    restart: always
    ports:
      - 5000:5000
    image: app
    links:
      - db
  nginx:
    image: sb-nginx:latest 
    restart: always
    ports:
      - 3000:80
    links:
      - app
     # Mount the volumes on the NGINX container
    volumes:
      # Mount the imagery from the 'branding' folder in the root of the container
      - type: bind
        source: ./client/build
        target: /frontend
        read_only: true

volumes:
  db: