version: "3.2"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - PGHOST=db
      - PGDATABASE=user
      - PGUSER=user
  app:
    build: .
    image: app
    restart: always
    ports:
      - 5000:5000
    image: app
    links:
      - db
  nginx:
    image: nginx
    restart: always
    ports:
      - 3000:80
    links:
      - app
    volumes:
      - type: bind
        source: ./client/build
        target: /frontend
        read_only: true



volumes:
  db: