version: "3.2"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build: .
    image: app
    restart: always
    ports:
      - 5000:5000
    image: app
    links:
      - db
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
  nginx:
    image: nginx:custom
    restart: always
    ports:
      - 80:80
    links:
      - app
    volumes:
      - type: bind
        source: ./client/build
        target: /frontend
        read_only: true



volumes:
  db: